# Basics

title: Tallas Goo | Professional Portfolio
url: "https://tallasgoo.github.io"
baseurl: ""

# Theme
bio-page-label: Resume
theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-2.html
theme-essays: theme-essays-builtin-2.html
theme-bio: theme-bio-builtin-1.html

# Miscellaneous
markdown: kramdown
include: [_data]
